### ISSUE TITLE
Add $(document).ready() function 

### ISSUE THREAD

**Issue by rcass** [julielo/Aloha-Project#1]
Add a $(document).ready() function around all your JavaScript code.

[Here is more info](https://learn.jquery.com/using-jquery-core/document-ready/)

Take it one step further and [write the shorthand](http://stackoverflow.com/questions/6004129/document-ready-shorthand)!

**Comment by julielo** [comment]
The shorthand version of the $(document).ready() function has been implemented into my JavaScript code.
