### ISSUE TITLE
CSS Issues

### ISSUE THREAD

**Issue by rcass** [julielo/Aloha-Project#3]
Here are some CSS issues I noticed on your project:

- [x] At all sizes, the hero image does not match the design. It is much larger (height wise) that the design. It is really noticeable in mobile.

- [x] In mobile, add some padding to the content sections to create white space from the text and the edge of the screen. This is will also make your design match the design more closely.

**Comment by julielo** [comment]
Fixed hero image for all sizes. The height now matches the design.

Added padding to the content sections. This change should now closely match the design.

**Comment by rcass** [comment]
👍  looks good
